on: 
  push: 
    branches:
      - main
      - 'release/*'
    paths:
      - "src/**"
  
  pull_request:
    branches:
      - main
      - "release/**"


jobs: 
  test:
    runs-on: ubuntu:latest
    steps:
    - name: Checkout the code 
      uses: actions/checkout@checkout@v6.1.0
    
    - name: Run test 
      run: npm test